name: Build and push Docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Docker build & push
    runs-on: ubuntu-latest
    steps:
    -
      name: Skip workflow
      run: echo 'skip this workflow'
